/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ActualizacionDeArticulos.java
 *
 * Created on 01-mar-2012, 13:00:28
 */
package siderconcapadatos;

import Excel.ExListadoArticulos;
import java.beans.PropertyVetoException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import objetos.Articulos;
import proceso.Procesos;
import siderconcapadatos.tablas.MiTablaArticulos;

/**
 *
 * @author Administrador
 */
public class ActualizacionDeArticulos extends javax.swing.JInternalFrame {

    /** Creates new form ActualizacionDeArticulos */
    private static ArrayList articulos=new ArrayList();
    private static ArrayList tablaCodigo=new ArrayList();
    public ActualizacionDeArticulos() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MiTablaArticulos TablaArticulos=new MiTablaArticulos();
        Procesos pro=new Procesos();
        try{
            articulos=pro.ListadoDeArticulos();
        }catch(Exception ex){
            System.err.println("NO SE CARGARON LOS ARTICULOS "+ex);
        }
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Actualizacion de Datos de Articulos Cargados en el Sistema HDR");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));

        jTable1.setModel(TablaArticulos);
        TablaArticulos.addColumn("Codigo Articulo");
        TablaArticulos.addColumn("Descripcion Articulo");
        TablaArticulos.addColumn("Sinonimo");
        TablaArticulos.addColumn("Peso Cargado");
        TablaArticulos.addColumn("Eliminar Articulo");
        Object[] fila=new Object[5];
        Iterator ia=articulos.listIterator();
        while(ia.hasNext()){
            Articulos art=null;
            art=(Articulos)ia.next();
            fila[0]=art.getCodigo();
            fila[1]=art.getDescripcionArticulo();
            fila[2]=art.getSinonimoArticulo();
            fila[3]=art.getPesoUnitario();
            fila[4]=false;
            TablaArticulos.addRow(fila);
        }
        jPanel3.setVisible(false);
        //tablaCodigo=articulos;
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 255), 1, true));

        jButton1.setText("Generar Excel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Buscar Codigo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Guardar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Buscar Sinonimo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Agregar Articulo");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton3))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel1.setText("Codigo Articulo :");

        jLabel2.setText("Descripcion");

        jLabel3.setText("Sinonimo :");

        jLabel4.setText("Peso Unitario :");

        jButton6.setText("Guardar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String codigo=JOptionPane.showInputDialog("POR FAVOR INGRESE EL CODIGO :");
        //codigo+="      ";
        //System.out.println("codigo ingresado"+codigo+"largo"+codigo.length());
        tablaCodigo.clear();;
        Articulos art=new Articulos();
        Boolean verificacion=false;
        Articulos seleccionado=null;
        Iterator ia=articulos.listIterator();
        //System.out.println("cantidad articulos "+articulos.size());
        while(ia.hasNext()){
            art=(Articulos)ia.next();
            String codigoArt=art.getCodigo();
            codigo.trim();
            int cantidad=codigo.length();
            codigoArt.trim();
            String cd=codigoArt.substring(0,cantidad);
            System.out.println("codigo Articulos"+codigoArt+" tamaño: "+codigoArt.length()+" cod ing "+codigo+" tamaño :"+codigo.length());
            if(codigo.equals(cd)){
                tablaCodigo.add(art);
                //seleccionado=art;
                verificacion=true;
                System.err.println("codigo Articulos"+codigoArt);
            }
        }
        if(verificacion){
        jTable1.removeAll();
        MiTablaArticulos tablaA=new MiTablaArticulos();

        tablaA.addColumn("Codigo Articulo");
        tablaA.addColumn("Descripcion Articulo");
        tablaA.addColumn("Sinonimo");
        tablaA.addColumn("Peso Cargado");
        tablaA.addColumn("Eliminar Articulo");
        Object[] fila=new Object[5];
        Iterator it=tablaCodigo.listIterator();
        while(it.hasNext()){
            seleccionado=(Articulos)it.next();
            String cod=seleccionado.getCodigo();
            String desc=seleccionado.getDescripcionArticulo();
            String sin=seleccionado.getSinonimoArticulo();
            Double peso=seleccionado.getPesoUnitario();
            fila[0]=cod;
            fila[1]=desc;
            fila[2]=sin;
            fila[3]=peso;
            fila[4]=false;
            tablaA.addRow(fila);
        }
        jTable1.setModel(tablaA);
        }else{
            JOptionPane.showMessageDialog(null,"ALERTA CODIGO NO ENCONTRADO","codigo no encontrado",JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String sinonimo=JOptionPane.showInputDialog("POR FAVOR INGRESE EL SINONIMO :");
        //codigo+="      ";
        //System.out.println("codigo ingresado"+codigo+"largo"+codigo.length());
        
        Articulos art=new Articulos();
        Boolean verificacion=false;
        Articulos seleccionado=null;
        tablaCodigo.clear();
        Iterator ia=articulos.listIterator();
        System.out.println("cantidad articulos "+articulos.size());
        while(ia.hasNext()){
            art=(Articulos)ia.next();
            String codigoArt=art.getSinonimoArticulo();
            sinonimo.trim();
            sinonimo=sinonimo.toUpperCase();
            int cantidad=sinonimo.length();
            System.out.println(codigoArt);
            //codigoArt.trim();
            String cd=null;
            if(codigoArt==null){
            cd="";
            }else{
                cd=codigoArt.substring(0,cantidad);
            }
                System.out.println("codigo Articulos"+cd+art.getCodigo()+" tamaño: "+cd.length()+" cod ing "+sinonimo+" tamaño :"+sinonimo.length());
            if(sinonimo.equals(cd)){
                tablaCodigo.add(art);
                //seleccionado=art;
                verificacion=true;
                System.err.println("sinonimo Articulos"+codigoArt+" tamaño:"+tablaCodigo.size());
            }
        }
        if(verificacion){
            
        jTable1.removeAll();
        MiTablaArticulos tablaA=new MiTablaArticulos();

        tablaA.addColumn("Codigo Articulo");
        tablaA.addColumn("Descripcion Articulo");
        tablaA.addColumn("Sinonimo");
        tablaA.addColumn("Peso Cargado");
        tablaA.addColumn("Eliminar Articulo");
        Object[] fila=new Object[5];
        Iterator it=tablaCodigo.listIterator();
        while(it.hasNext()){
            seleccionado=(Articulos)it.next();
            String cod=seleccionado.getCodigo();
            String desc=seleccionado.getDescripcionArticulo();
            String sin=seleccionado.getSinonimoArticulo();
            Double peso=seleccionado.getPesoUnitario();
            fila[0]=cod;
            fila[1]=desc;
            fila[2]=sin;
            fila[3]=peso;
            fila[4]=false;
            tablaA.addRow(fila);
        }
        jTable1.setModel(tablaA);
        //articulos.clear();
        //articulos=tablaCodigo;
        }else{
            JOptionPane.showMessageDialog(null,"ALERTA SINONIMO NO ENCONTRADO","sinonimo no encontrado",JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ArrayList paraEnvio=null;
        if(tablaCodigo.size()>0){
            paraEnvio=tablaCodigo;
        }else{
            paraEnvio=articulos;
        }
        int cantidad=jTable1.getRowCount();
        Articulos ar=new Articulos();
        for(int i=0;i<cantidad;i++){
            int esst=0;
            ar=(Articulos) paraEnvio.get(i);
            String descripcion=(String) jTable1.getValueAt(i,1);
            String sinonimo=(String) jTable1.getValueAt(i,2);
            Double peso=(Double) jTable1.getValueAt(i,3);
            Boolean est=(Boolean) jTable1.getValueAt(i,4);
            ar.setDescripcionArticulo(descripcion);
            ar.setSinonimoArticulo(sinonimo);
            ar.setPesoUnitario(peso);
            if(est)esst=2;
            ar.setEstado(esst);
        }
        Procesos pr=new Procesos();
        try {
            pr.ModificacionDeArticulos(paraEnvio);
        } catch (SQLException ex) {
            Logger.getLogger(ActualizacionDeArticulos.class.getName()).log(Level.SEVERE, null, ex);
        }
        setDefaultCloseOperation(DISPOSE_ON_CLOSE); 
        try {
            setClosed(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(ActualizacionDeArticulos.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jPanel1.setVisible(false);
        jPanel3.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Articulos art=new Articulos();
        String codigo=jTextField1.getText();
        String sinonimo=jTextField3.getText();
        String descripcion=jTextField2.getText();
        String pp=this.jTextField4.getText().replace(",",".");
        Double peso=Double.parseDouble(pp);
        art.setCodigo(codigo.trim());
        art.setDescripcionArticulo(descripcion.trim());
        art.setSinonimoArticulo(sinonimo.trim());
        art.setPesoUnitario(peso);
        art.setEstado(3);
        Procesos prart=new Procesos();
        try {
            prart.GuardarNuevoArticulo(art);
        } catch (SQLException ex) {
            Logger.getLogger(ActualizacionDeArticulos.class.getName()).log(Level.SEVERE, null, ex);
        }
        setDefaultCloseOperation(DISPOSE_ON_CLOSE); 
        try {
            setClosed(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(ActualizacionDeArticulos.class.getName()).log(Level.SEVERE, null, ex);
        }     
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ExListadoArticulos ex=new ExListadoArticulos();
        if(tablaCodigo.size() > 0){
         ex.GenerarInforme(tablaCodigo);   
        }else{
        ex.GenerarInforme(articulos);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        tablaCodigo.clear();
        articulos.clear();
    }//GEN-LAST:event_formInternalFrameClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
