/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DetallePendientes.java
 *
 * Created on 16-mar-2012, 14:16:59
 */
package siderconcapadatos;

import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;
import objetos.PedidosParaReparto;
import proceso.Procesos;

/**
 *
 * @author Administrador
 */
public class DetallePendientes extends javax.swing.JInternalFrame {

    /** Creates new form DetallePendientes */
    private static String pedido;
    private static String codigo;
    public DetallePendientes(String ped) {
        pedido=ped;
        //codigo=cod;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DefaultTableModel st=new DefaultTableModel();
        Procesos pr=new Procesos();
        PedidosParaReparto ped=new PedidosParaReparto();
        ArrayList listado=new ArrayList();
        try{
            listado=pr.DetalleDeEntregasMaterialesPendientes(pedido);
        }catch(Exception ex){
            System.out.println("No se cargo el detalle "+ex);
        }
        st.addColumn("Articulo");
        st.addColumn("Descripcion");
        st.addColumn("Cantidad Entregada");
        st.addColumn("Fecha Asignada");
        st.addColumn("Vehiculo asignado");
        Iterator il=listado.listIterator();
        Object[] fila=new Object[5];
        while(il.hasNext()){
            ped=(PedidosParaReparto)il.next();
            fila[0]=ped.getCodigoArticulo();
            fila[1]=ped.getDescripcionArticulo();
            fila[2]=ped.getCantidadArticulo();
            fila[3]=ped.getFechaEnvio();
            fila[4]=ped.getVehiculoAsignado();
            st.addRow(fila);
        }
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Detalle Material Entregado");

        jTable1.setModel(st);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
