/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ModificacionDePedidos.java
 *
 * Created on 03-feb-2012, 12:01:39
 */
package siderconcapadatos;

import interfaces.Editables;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import objetos.Mail;
import objetos.PedidosParaReparto;

/**
 *
 * @author Administrador
 */
public class EliminacionDePedidos extends javax.swing.JInternalFrame {

    /** Creates new form ModificacionDePedidos */
    private ArrayList listadoDelPedido;
    private String nmPedido;
    private PedidosParaReparto origen;

    
    
    public EliminacionDePedidos(String pedido) {
        nmPedido=pedido;
        
        initComponents();
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Eliminación de Pedidos");
        setVisible(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/logo.png")));
        jButton1.setText("Eliminar ");
        jButton1.setToolTipText("Presione para guardar las modificaciones o eliminaciones en el pedido actual");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("<html>PARA LA ELIMINACION DE UNO O VARIOS ITEMS:<br> \t-Marcar el checkbox correspondiente al item a eliminar<br>\t-Una vez marcado el/los items, presionar Eliminar<br>\t-Si la intención es eliminar el pedido completo dejar marcados todos los Imtes y presione Eliminar</html>");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

         int total=this.jTable1.getRowCount();
         Editables editable=new PedidosParaReparto();
         int cantidad=0;
         for(int b=0;b < total;b++){
             if((Boolean)this.jTable1.getValueAt(b, 6)){
                 //origen=(PedidosParaReparto) listadoDelPedido.get(b);
                 //editable.EliminarItems(origen.getiDPedido());
                 cantidad++;
             }
         }
         if(cantidad > 0){
            if(JOptionPane.showConfirmDialog(this,"Confirma que Elimina los "+cantidad+" ítems del pedido seleccionado?","Eliminación de Movimientos de Pedidos",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE)==1){

            }else{
                String motivo=JOptionPane.showInputDialog("Ingrese Motivo de la eliminación, por Favor");
                Mail mail=new Mail();
                ArrayList eliminables=new ArrayList();
               for(int a=0;a < total;a++){
                   if((Boolean)this.jTable1.getValueAt(a, 6)){
                       origen=(PedidosParaReparto) listadoDelPedido.get(a);
                       eliminables.add(origen);
                       editable.EliminarItems(origen.getiDPedido());
                       //cantidad++;
                   }
               }
               JOptionPane.showMessageDialog(this,"ELIMINADOS "+cantidad+" ITEMS DEL SISTEMA HDR");
               String encab="Anulación de Pedido en Reparto "+SiderconCapaatos.fecha+" - "+origen.getEmpresa()+" - "+origen.getCodigoTangoDePedido()+" - "+origen.getRazonSocial();
               mail.enviarMailDeEliminacionDePedido(encab,eliminables,motivo);
               this.dispose();
            }
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        Editables edi=new PedidosParaReparto();
        listadoDelPedido=edi.ListarDetalleDePedidos(nmPedido);
        Editables edita=new PedidosParaReparto();
        this.jTable1.setModel(edita.MostrarEnTabla(listadoDelPedido));
        
    }//GEN-LAST:event_formInternalFrameActivated

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
